---
label: Producto
hide_body: false
fields:
- name: date
  type: datetime
  label: Fecha
  description: ''
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  hidden: true
  default: now
- name: title
  type: text
  config:
    required: true
  label: Título de la publicacion
  description: Indica el título de la publicación. <strong>Evita colocar el precio
    en el título!</strong>
- name: unit_price
  type: text
  config:
    required: true
  label: Precio del producto
  description: Precio del producto sin <strong>"$"</strong> o <strong>"COP"</strong>.
    p.ej. 160.000
- name: description
  type: text
  config:
    required: true
  label: Descripción
  description: Corta y breve descripción del producto
- name: category
  type: select
  default: Piedras preciosas
  config:
    required: true
    options:
    - Piedras preciosas
    - Semi preciosas
    - Fósil
    - Raras
    - Otros
    - Meteoritos
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Categoría
  description: Indica la categoría del producto
- name: cover_img
  type: file
  config:
    maxSize: 64
  label: Foto de portada
  description: Foto de portada del producto
- name: images
  type: image_gallery
  config: {}
  label: Fotos del producto
  description: Evita subir fotos con la extensión en mayuscula. p.ej. <strong>.JPG,
    .PNG</strong>, etc
- name: available
  type: boolean
  label: Producto disponible
  description: Indica si el producto esta disponible
  default: true
pages:
- products/apophyllite-natural-piedra-preciosa-149-gramos.md
- products/coral-cristalizado-piedra-natural-393-gramos.md
- products/coral-rojo-perforada-piedra-natura-73-08-quilates-42-000.md
- products/cuarzo-arcoiris-turmalinado-piedra-natural-299-quilates.md
- products/cuarzo-citrino-fantasma-piedra-natural-250-quilates.md
- products/cuarzo-devico-piedra-100-natural-222-gramos.md
- products/cuarzo-fluorescente-piedra-natural-110-gramos.md
- products/cuarzo-lemuriano-amarillo-piedra-natural-186-20-quilates.md
- products/cuarzo-lemuriano-rojo-piedra-natural-147-05-quilates.md
- products/cuarzo-negro-piedra-natural-143-45-quilates.md
- products/cuarzo-negro-rumano-piedra-natural-207-quilates.md
- products/cuarzo-rutilo-de-oro-piedra-natural-215-80-quilates-1.md
- products/cuarzo-rutilo-de-oro-piedra-natural-332-quilates.md
- products/cuarzo-rutilo-de-oro-piedra-natural-348-80-quilates.md
- products/cuarzo-rutilo-turmalina-piedra-100-natural.md
- products/diamante-100-natural-0-16-quilates.md
- products/diamante-100-natural-0-20-quilates.md
- products/diamante-100-natural-0-21-quilates.md
- products/diamante-100-natural-0-25-quilates.md
- products/diamante-100-natural-0-26-quilates.md
- products/drusa-cuarzo-lemuriano-piedra-natural-111-gramos.md
- products/drusa-cuarzo-rojo-piedra-natural-152-gramos.md
- products/esmeralda-morganita-certificada-2-69-quilates.md
- products/esmeralda-trapiche-cabeza-de-marciano-certificada-6-26-quilates.md
- products/esmeralda-trapiche-certificada-4-06-quilates.md
- products/henossita-natural-piedra-preciosa-1-85-quilates-150-000.md
- products/lote-2-diamantes-100-naturales-0-51-quilates.md
- products/lote-de-31-diamantes-1-23-quilates-piedra-100-natural.md
- products/lote-de-64-diamantes-0-95-quilates-piedra-100-natural.md
- products/meteorito-cristal-negro-piedra-natural.md
- products/ojo-de-buey-piedra-100-natural-28-30-quilates.md
- products/piedra-onix-cielo-piedra-natural-kilo-50-000.md
