---
label: Producto
hide_body: false
fields:
- name: date
  type: datetime
  label: Fecha
  description: ''
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  hidden: true
  default: now
- name: title
  type: text
  config:
    required: true
  label: Título de la publicacion
  description: Indica el título de la publicación. <strong>Evita colocar el precio
    en el título!</strong>
- name: unit_price
  type: text
  config:
    required: true
  label: Precio del producto
  description: Precio del producto sin <strong>"$"</strong> o <strong>"COP"</strong>.
    p.ej. 160.000
- name: description
  type: text
  config:
    required: true
  label: Descripción
  description: Corta y breve descripción del producto
- name: category
  type: select
  default: Piedras preciosas
  config:
    required: true
    options:
    - Piedras preciosas
    - Semi preciosas
    - Fósil
    - Raras
    - Otros
    - Meteoritos
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Categoría
  description: Indica la categoría del producto
- name: cover_img
  type: file
  config:
    maxSize: 64
  label: Foto de portada
  description: Foto de portada del producto
- name: images
  type: image_gallery
  config: {}
  label: Fotos del producto
  description: Evita subir fotos con la extensión en mayuscula. p.ej. <strong>.JPG,
    .PNG</strong>, etc
- name: available
  type: boolean
  label: Producto disponible
  description: Indica si el producto esta disponible
  default: true
pages:
- products/agata-de-madagascar-piedra-natural-305-quilates.md
- products/agata-de-madagascar-piedra-natural-395-quilates.md
- products/agata-de-madagascar-piedra-natural-465-quilates.md
- products/agata-de-seda-piedra-natural-101-gramos.md
- products/agata-de-seda-piedra-natural-102-gramos.md
- products/agata-de-seda-piedra-natural-103-gramos.md
- products/agata-de-seda-piedra-natural-112-gramos.md
- products/agata-de-seda-piedra-natural-134-gramos.md
- products/agata-de-seda-piedra-natural-140-quilates.md
- products/agata-de-seda-piedra-natural-175-quilates.md
- products/agata-de-seda-piedra-natural-225-quilates.md
- products/agata-de-seda-piedra-natural-245-quilates.md
- products/agata-de-seda-piedra-natural-248-gramos.md
- products/agata-de-seda-piedra-natural-310-quilates.md
- products/agata-de-seda-piedra-natural-320-quilates.md
- products/agata-de-seda-piedra-natural-355-quilates.md
- products/agata-de-seda-piedra-natural-365-quilates-1.md
- products/agata-de-seda-piedra-natural-365-quilates.md
- products/agata-de-seda-piedra-natural-370-quilates.md
- products/agata-de-seda-piedra-natural-385-quilates.md
- products/agata-de-seda-piedra-natural-410-quilates.md
- products/agata-de-seda-piedra-natural-420-quilates.md
- products/agata-de-seda-piedra-natural-470-quilates.md
- products/agata-seda-de-madagascar-piedra-natural-103-gramos.md
- products/agata-seda-de-madagascar-piedra-natural-114-gramos.md
- products/agata-seda-de-madagascar-piedra-natural-131-gramos.md
- products/agata-seda-de-madagascar-piedra-natural-134-gramos.md
- products/agata-seda-de-madagascar-piedra-natural-160-gramos-1.md
- products/agata-seda-de-madagascar-piedra-natural-160-gramos.md
- products/agata-seda-de-madagascar-piedra-natural-248-gramos.md
- products/ammolita-piedra-fosil-natural-176-gramos.md
- products/apophyllite-natural-piedra-preciosa-149-gramos.md
- products/azurita-piedra-100-natural-33-quilates.md
- products/boguel-cuarzo-lemuriano-piedra-natural-145-05-quilates.md
- products/boguel-cuarzo-lemuriano-piedra-natural-160-quilates.md
- products/boguel-cuarzo-lemuriano-piedra-natural-165-60-ct.md
- products/boguel-cuarzo-lemuriano-piedra-natural-176-45-quilates.md
- products/boguel-cuarzo-lemuriano-piedra-natural-186-74-quilates.md
- products/boguel-de-cuarzo-rosado-piedra-natural-100-gramos.md
- products/coral-cristalizado-piedra-natural-393-gramos.md
- products/coral-fosil-piedra-natural-75.60-quilates.md
- products/coral-rojo-perforada-piedra-natura-73-08-quilates-42-000.md
- products/cuarzo-ahumado-con-turmalina-piedra-natural-220-gramos.md
- products/cuarzo-ahumado-piedra-100-natural-162-gramos-1.md
- products/cuarzo-arcoiris-turmalinado-piedra-natural-299-quilates.md
- products/cuarzo-cereza-piedra-natural-18-40-quilates.md
- products/cuarzo-citrino-fantasma-piedra-natural-205-quilates.md
- products/cuarzo-citrino-fantasma-piedra-natural-250-quilates.md
- products/cuarzo-citrino-piedra-natural-64-65-quilates.md
- products/cuarzo-cristal-piedra-natural-58-25-quilates.md
- products/cuarzo-de-agua-92-quilates-piedra-natural.md
- products/cuarzo-de-fuego-piedra-100-natural-357-quilates.md
- products/cuarzo-de-fuego-piedra-natural-357-quilates.md
- products/cuarzo-devico-piedra-100-natural-222-gramos.md
- products/cuarzo-fantasma-marrón-piedra-natural-220-quilates.md
- products/cuarzo-fantasma-verde-100-natural-52-quilates.md
- products/cuarzo-fantasma-verde-piedra-natural-214-90-quilates.md
- products/cuarzo-fantasma-verde-piedra-natural-234-60-ct.md
- products/cuarzo-fluorescente-piedra-natural-110-gramos.md
- products/cuarzo-jacinto-piedra-natural-83-80-quilates.md
- products/cuarzo-lemuriano-amarillo-piedra-natural-186-20-quilates.md
- products/cuarzo-lemuriano-rojo-piedra-natural-142-50-ct.md
- products/cuarzo-lemuriano-rojo-piedra-natural-147-05-quilates.md
- products/cuarzo-lemuriano-rojo-piedra-natural-276-20-quilates.md
- products/cuarzo-negro-gemelo-piedra-100-natural-315-quilates.md
- products/cuarzo-negro-gemelo-piedra-natural-94-45-quilates.md
- products/cuarzo-negro-piedra-natural-143-45-quilates.md
- products/cuarzo-negro-rumano-piedra-natural-207-quilates.md
- products/cuarzo-prasio-con-calcita-piedra-natural-42-25-ct.md
- products/cuarzo-prasio-con-calcita-piedra-natural-52-quilates.md
- products/cuarzo-prasio-piedra-100-natural-48-70-quilates.md
- products/cuarzo-prasio-piedra-100-natural-54-95-quilates.md
- products/cuarzo-prasio-piedra-natural-57-25-quilates.md
- products/cuarzo-rojo-piedra-natural-56-15-quilates-30-000.md
- products/cuarzo-rubi-con-carborundun-piedra-natural-81-quilates.md
- products/cuarzo-rutilado-piedra-natural-255-quilates.md
- products/cuarzo-rutilado-rojo-piedra-natural-154-quilates.md
- products/cuarzo-rutilo-de-oro-piedra-natural-215-80-quilates-1.md
- products/cuarzo-rutilo-de-oro-piedra-natural-332-quilates.md
- products/cuarzo-rutilo-de-oro-piedra-natural-348-80-quilates.md
- products/cuarzo-rutilo-turmalina-piedra-100-natural.md
- products/diamante-100-natural-0-16-quilates.md
- products/diamante-100-natural-0-20-quilates.md
- products/diamante-100-natural-0-21-quilates.md
- products/diamante-100-natural-0-25-quilates.md
- products/diamante-100-natural-0-26-quilates.md
- products/dije-de-azabache-natural-50.80-quilates.md
- products/dije-de-sodalita-piedra-natural-143.05-quilates.md
- products/drusa-cuarzo-lemuriano-piedra-natural-111-gramos.md
- products/drusa-cuarzo-rojo-piedra-natural-152-gramos.md
- products/epidota-zoisita-piedra-100-natural-18.35-quilates.md
- products/epidota-zoisita-piedra-100-natural-18.95-quilates-0.md
- products/esmeralda-cabujon-piedra-natural-1-00-quilates.md
- products/esmeralda-cabujon-piedra-natural-1-15-quilates.md
- products/esmeralda-cabujon-piedra-natural-1-56-quilates.md
- products/esmeralda-cabujon-piedra-natural-4-61-quilates.md
- products/esmeralda-cabujon-piedra-natural-5-65-quilates.md
- products/esmeralda-cuarzo-pirita-octaedrica-piedra-natural.md
- products/esmeralda-morganita-certificada-2-69-quilates.md
- products/esmeralda-piedra-natural-2-42-quilates.md
- products/esmeralda-trapiche-cabeza-de-marciano-certificada-6-26-quilates.md
- products/esmeralda-trapiche-certificada-4-06-quilates.md
- products/fluorita-piedra-natural-323-gramos.md
- products/henossita-natural-piedra-preciosa-1-85-quilates-150-000.md
- products/jade-dije-natural-291-80-quilates.md
- products/lote-2-diamantes-100-naturales-0-51-quilates.md
- products/lote-de-31-diamantes-1-23-quilates-piedra-100-natural.md
- products/lote-de-64-diamantes-0-95-quilates-piedra-100-natural.md
- products/meteorito-cristal-negro-piedra-natural.md
- products/obelisco-cuarzo-ahumado-piedra-natural-260-quilates.md
- products/ojo-de-buey-piedra-100-natural-28-30-quilates.md
- products/ojo-de-tigre-piedra-100-natural-172-quilates.md
- products/opalina-piedra-preciosa-135.70-quilates.md
- products/peridoto-piedra-cultivada-50.15-quilates.md
- products/piedra-esfera-calcita-amarilla-237-gramos.md
- products/piedra-esfera-cuarzo-bismuto-245-quilates.md
- products/piedra-esfera-cuarzo-citrino-466.70-ct.md
- products/piedra-onix-cielo-piedra-natural-kilo-50-000.md
- products/piedra-preciosa-amatista-herkimer-93-85-quilates.md
- products/piedra-preciosa-azurita-con-malaquita-439-quilates.md
- products/piedra-preciosa-coral-fosilizado-87.20-quilates.md
- products/piedra-preciosa-cuarzo-lemuriano-rojo-127-40-quilates.md
- products/piedra-preciosa-cuarzo-negro-rumano-160-90-quilates.md
- products/piedra-preciosa-feldespato-natural-417.15-quilates.md
- products/piedra-preciosa-ojo-de-tigre-152-22-quilates.md
- products/piedra-preciosa-oropimente-natural-114-gramos.md
- products/rodocrosita-piedra-preciosa-143.15-quilates.md
- products/rodocrosita-piedra-preciosa-99.45-quilates.md
- products/ágata-de-seda-piedra-natural-445-quilates.md
- products/ágata-de-seda-rosada-piedra-natural-370-quilates.md
