---
label: Producto
hide_body: false
fields:
- name: date
  type: datetime
  label: Fecha
  description: ''
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  hidden: true
  default: now
- name: title
  type: text
  config:
    required: true
  label: Título de la publicacion
  description: Indica el título de la publicación. <strong>Evita colocar el precio
    en el título!</strong>
- name: unit_price
  type: text
  config:
    required: true
  label: Precio del producto
  description: Precio del producto sin <strong>"$"</strong> o <strong>"COP"</strong>.
    p.ej. 160.000
- name: description
  type: text
  config:
    required: true
  label: Descripción
  description: Corta y breve descripción del producto
- name: category
  type: select
  default: Piedras preciosas
  config:
    required: true
    options:
    - Piedras preciosas
    - Semi preciosas
    - Fósil
    - Raras
    - Otros
    - Meteoritos
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Categoría
  description: Indica la categoría del producto
- name: cover_img
  type: file
  config:
    maxSize: 64
  label: Foto de portada
  description: Foto de portada del producto
- name: images
  type: image_gallery
  config: {}
  label: Fotos del producto
  description: Evita subir fotos con la extensión en mayuscula. p.ej. <strong>.JPG,
    .PNG</strong>, etc
- name: available
  type: boolean
  label: Producto disponible
  description: Indica si el producto esta disponible
  default: true
pages:
- products/11.25-quilates.md
- products/55.55-quilates.md
- products/acondrita-meteorito-rocoso-235-quilates.md
- products/acondrita-meteorito-rocoso-240-quilates.md
- products/agata-de-fuego-piedra-natural-17.10-quilates.md
- products/agata-de-fuego-piedra-natural-17.45-quilates.md
- products/agata-de-fuego-piedra-natural-18.25-quilates.md
- products/agata-de-fuego-piedra-natural-19.80-quilates.md
- products/agata-de-fuego-piedra-natural-26.55-quilates.md
- products/agata-de-fuego-piedra-natural-3-37-quilates.md
- products/agata-de-fuego-piedra-natural-6.20-quilates.md
- products/agata-de-fuego-piedra-natural-6.47-quilates.md
- products/agata-de-fuego-piedra-natural-79.20-quilates.md
- products/agata-de-fuego-piedra-natural-8.83-quilates.md
- products/agata-de-fuego.md
- products/agata-de-madagascar-piedra-natural-305-quilates.md
- products/agata-de-madagascar-piedra-natural-395-quilates.md
- products/agata-de-madagascar-piedra-natural-465-quilates.md
- products/agata-de-seda-piedra-natural-101-gramos.md
- products/agata-de-seda-piedra-natural-102-gramos.md
- products/agata-de-seda-piedra-natural-103-gramos.md
- products/agata-de-seda-piedra-natural-112-gramos.md
- products/agata-de-seda-piedra-natural-134-gramos.md
- products/agata-de-seda-piedra-natural-140-quilates.md
- products/agata-de-seda-piedra-natural-175-quilates.md
- products/agata-de-seda-piedra-natural-225-quilates.md
- products/agata-de-seda-piedra-natural-245-quilates.md
- products/agata-de-seda-piedra-natural-248-gramos.md
- products/agata-de-seda-piedra-natural-310-quilates.md
- products/agata-de-seda-piedra-natural-320-quilates.md
- products/agata-de-seda-piedra-natural-355-quilates.md
- products/agata-de-seda-piedra-natural-365-quilates-1.md
- products/agata-de-seda-piedra-natural-365-quilates.md
- products/agata-de-seda-piedra-natural-370-quilates.md
- products/agata-de-seda-piedra-natural-385-quilates.md
- products/agata-de-seda-piedra-natural-410-quilates.md
- products/agata-de-seda-piedra-natural-420-quilates.md
- products/agata-de-seda-piedra-natural-470-quilates.md
- products/agata-dentrica-100-natural-350-quilates.md
- products/agata-dentrica-dije-piedra-natural-100-51-quilates.md
- products/agata-dentritica.md
- products/agata-musgosa-100-natural-54.33-quilates.md
- products/agata-piedra-natural-32.23-quilates.md
- products/agata-piel-de-dragon-100-natural-31.90-quilates.md
- products/agata-piel-de-dragon-100-natural-75-quilates.md
- products/agata-seda-de-madagascar-piedra-natural-103-gramos.md
- products/agata-seda-de-madagascar-piedra-natural-114-gramos.md
- products/agata-seda-de-madagascar-piedra-natural-131-gramos.md
- products/agata-seda-de-madagascar-piedra-natural-134-gramos.md
- products/agata-seda-de-madagascar-piedra-natural-160-gramos-1.md
- products/agata-seda-de-madagascar-piedra-natural-160-gramos.md
- products/agata-seda-de-madagascar-piedra-natural-248-gramos.md
- products/amatista-lavanda.md
- products/ammolita-piedra-fosil-natural-176-gramos.md
- products/ammolita-piedra-fosil-natural-201-quilates.md
- products/amonita-en-pirita-fosil-100-natural-345-quilates.md
- products/amonita-piedra-fosil-natural-140-quilates.md
- products/amonita-piedra-fosil-natural-176-gramos.md
- products/amonita-piedra-fosil-natural-182-gramos.md
- products/amonita-piedra-fosil-natural-270-quilates.md
- products/apophyllite-natural-piedra-preciosa-149-gramos.md
- products/aventurina-piedra-100-natural-28.35-quilates.md
- products/azurita-100-natural-55.00.md
- products/azurita-piedra-100-natural-33-quilates.md
- products/azurita-piedra-100-natural-69-quilates.md
- products/boguel-cuarzo-lemuriano-piedra-natural-145-05-quilates.md
- products/boguel-cuarzo-lemuriano-piedra-natural-160-quilates.md
- products/boguel-cuarzo-lemuriano-piedra-natural-165-60-ct.md
- products/boguel-cuarzo-lemuriano-piedra-natural-176-45-quilates.md
- products/boguel-cuarzo-lemuriano-piedra-natural-186-74-quilates.md
- products/boguel-de-cuarzo-rosado-piedra-natural-100-gramos.md
- products/broncita-piedra-100-natural-44.85-quilates.md
- products/calcantita-piedra-preciosa-402-gramos.md
- products/celestita-cuarzo-azul-piedra-100-natural-66-quilates.md
- products/citrino-imperial-piedra-100-natural-2.10-quilates.md
- products/coleccion-billetes-varios-paises-y-denominaciones.md
- products/coleccion-de-20-aviones-de-combate-a-escala.md
- products/coral-cristalizado-piedra-natural-393-gramos.md
- products/coral-fosil-piedra-natural-75.60-quilates.md
- products/coral-rojo-perforada-piedra-natura-73-08-quilates-42-000.md
- products/crisocola-piedra-semipreciosa-natural-51.05-quilates.md
- products/cristal-de-desierto-piedra-100-natural-7.20-quilates.md
- products/cruz-de-hierro-100-natural-53-quilates.md
- products/cuarzo-ahumado-con-turmalina-piedra-natural-220-gramos.md
- products/cuarzo-ahumado-piedra-100-natural-162-gramos-1.md
- products/cuarzo-arcoiris-1.md
- products/cuarzo-arcoiris-turmalinado-piedra-natural-299-quilates.md
- products/cuarzo-arcoiris.md
- products/cuarzo-azul-celestita-100-natural-92-quilates.md
- products/cuarzo-bogue-fantasma-100-natural-132-quilates.md
- products/cuarzo-castillo-fantasma-100-natural-103.85-quilates.md
- products/cuarzo-cereza-piedra-natural-18-40-quilates.md
- products/cuarzo-citrino-fantasma-piedra-natural-205-quilates.md
- products/cuarzo-citrino-fantasma-piedra-natural-250-quilates.md
- products/cuarzo-citrino-piedra-natural-64-65-quilates.md
- products/cuarzo-con-bismuto-piedra-natural-111.65-quilates.md
- products/cuarzo-con-bismuto-piedra-natural-125-quilates.md
- products/cuarzo-con-bismuto-piedra-natural-85.55-quilates.md
- products/cuarzo-cristal-piedra-natural-58-25-quilates.md
- products/cuarzo-de-agua-92-quilates-piedra-natural.md
- products/cuarzo-de-fuego-piedra-100-natural-357-quilates.md
- products/cuarzo-de-fuego-piedra-natural-357-quilates.md
- products/cuarzo-devico-piedra-100-natural-222-gramos.md
- products/cuarzo-epidoto-100.md
- products/cuarzo-epidoto-14-quilates.md
- products/cuarzo-fantasma-100-natural-46-quilates.md
- products/cuarzo-fantasma-100-natural-53-quilates.md
- products/cuarzo-fantasma-100-natural-54-quilates.md
- products/cuarzo-fantasma-100-natural-92-quilates.md
- products/cuarzo-fantasma-marrón-piedra-natural-220-quilates.md
- products/cuarzo-fantasma-piramidal-100-natural-113-quilates.md
- products/cuarzo-fantasma-piramidal-100-natural-52-quilates.md
- products/cuarzo-fantasma-verde-100-natural-52-quilates.md
- products/cuarzo-fantasma-verde-piedra-natural-214-90-quilates.md
- products/cuarzo-fantasma-verde-piedra-natural-234-60-ct.md
- products/cuarzo-fluorescente-piedra-natural-110-gramos.md
- products/cuarzo-jacinto-piedra-natural-83-80-quilates.md
- products/cuarzo-lemuriano-amarillo-piedra-natural-186-20-quilates.md
- products/cuarzo-lemuriano-piedra-100-natural-7.60-quilates.md
- products/cuarzo-lemuriano-rojo-piedra-natural-142-50-ct.md
- products/cuarzo-lemuriano-rojo-piedra-natural-147-05-quilates.md
- products/cuarzo-lemuriano-rojo-piedra-natural-276-20-quilates.md
- products/cuarzo-marron-lemuriano-piedra-100-natural-153-quilates.md
- products/cuarzo-negro-gemelo-piedra-100-natural-315-quilates.md
- products/cuarzo-negro-gemelo-piedra-natural-94-45-quilates.md
- products/cuarzo-negro-piedra-natural-143-45-quilates.md
- products/cuarzo-negro-rumano-piedra-natural-207-quilates.md
- products/cuarzo-prasio-con-calcita-piedra-natural-42-25-ct.md
- products/cuarzo-prasio-con-calcita-piedra-natural-52-quilates.md
- products/cuarzo-prasio-piedra-100-natural-48-70-quilates.md
- products/cuarzo-prasio-piedra-100-natural-54-95-quilates.md
- products/cuarzo-prasio-piedra-natural-57-25-quilates.md
- products/cuarzo-rojo-piedra-natural-56-15-quilates-30-000.md
- products/cuarzo-rubi-con-carborundun-piedra-natural-81-quilates.md
- products/cuarzo-rutilado-piedra-natural-255-quilates.md
- products/cuarzo-rutilo-de-oro-100-natural-33.40-quilates.md
- products/cuarzo-rutilo-de-oro-piedra-natural-215-80-quilates-1.md
- products/cuarzo-rutilo-de-oro-piedra-natural-332-quilates.md
- products/cuarzo-rutilo-de-oro-piedra-natural-348-80-quilates.md
- products/cuarzo-rutilo-rojo-100-natural-154.35-quilates.md
- products/cuarzo-rutilo-turmalina-piedra-100-natural.md
- products/cuarzo-solar-100-natural-16.85-quilates.md
- products/cuarzo-solar-100-natural-6.75-quilates.md
- products/cuarzo-solar-100-natural-7.85-quilates.md
- products/cuarzo-verde-fantasma-100-natural-24-quilates.md
- products/damburita-piedra-100-natural-5-66-quilates.md
- products/diamante-100-natural-0-16-quilates.md
- products/diamante-100-natural-0-20-quilates.md
- products/diamante-100-natural-0-21-quilates.md
- products/diamante-100-natural-0-25-quilates.md
- products/diamante-100-natural-0-26-quilates.md
- products/diamante-herkimer-fantasma-100-natural-28-quilates.md
- products/dije-de-azabache-natural-50.80-quilates.md
- products/dije-de-sodalita-piedra-natural-143.05-quilates.md
- products/diopsido-estrella-natural-certificado-3.64-quilates.md
- products/diopsido-estrella-piedra-preciosa-11.70-quilates.md
- products/drusa-cuarzo-cristal-100-natural-119-gramos.md
- products/drusa-cuarzo-cristal-100-natural-181-gramos.md
- products/drusa-cuarzo-cristal-100-natural-215-gramos.md
- products/drusa-cuarzo-cristal-100-natural-2210-gramos.md
- products/drusa-cuarzo-cristal-100-natural-227-gramos.md
- products/drusa-cuarzo-cristal-100-natural-229-gramos.md
- products/drusa-cuarzo-cristal-100-natural-281-gramos.md
- products/drusa-cuarzo-cristal-100-natural-412-gramos.md
- products/drusa-cuarzo-cristal-100-natural-451-gramos.md
- products/drusa-cuarzo-cristal-100-natural-491-gramos.md
- products/drusa-cuarzo-cristal-100-natural-500-gramos.md
- products/drusa-cuarzo-cristal-piedra-natural-55-gramos.md
- products/drusa-cuarzo-cristal-y-ahumado-2576-gramos.md
- products/drusa-cuarzo-cristal-y-rojo-lemuriano-1018-gramos.md
- products/drusa-cuarzo-lemuriano-piedra-natural-111-gramos.md
- products/drusa-cuarzo-rojo-piedra-natural-152-gramos.md
- products/drusa-de-amatista-de-veracruz-155-quilates.md
- products/drusa-de-amatista-de-veracruz-180-quilates.md
- products/drusa-de-amatista-de-veracruz-200-quilates.md
- products/drusa-de-amatistas-de-veracruz-210-quilates.md
- products/drusa-de-amatistas-de-veracruz-235-quilates.md
- products/drusa-de-amatistas-de-veracruz-250-quilates.md
- products/drusa-de-amatistas-de-veracruz-35-quilates.md
- products/drusa-de-amatistas-de-veracruz-50-quilates.md
- products/drusa-de-amatistas-de-veracruz-625-quilates.md
- products/drusa-de-amatistas-de-veracruz-75-quilates.md
- products/drusa-de-amatistas-de-veracruz-80-quilates.md
- products/drusa-de-amatistas-de-veracruz-95-quilates.md
- products/epidota-zoisita-piedra-100-natural-18.35-quilates.md
- products/epidota-zoisita-piedra-100-natural-18.95-quilates-0.md
- products/escapolita-piedra-100-natural-11.25-quilates.md
- products/escapolita-piedra-100-natural-7.59-quilates.md
- products/esmeralda-cabujon-piedra-natural-1-00-quilates.md
- products/esmeralda-cabujon-piedra-natural-1-15-quilates.md
- products/esmeralda-cabujon-piedra-natural-1-56-quilates.md
- products/esmeralda-cabujon-piedra-natural-4-61-quilates.md
- products/esmeralda-cabujon-piedra-natural-5-65-quilates.md
- products/esmeralda-cuarzo-pirita-octaedrica-piedra-natural.md
- products/esmeralda-morganita-certificada-2-69-quilates.md
- products/esmeralda-piedra-natural-2-42-quilates.md
- products/esmeralda-piedra-natural-2.42-quilates.md
- products/esmeralda-trapiche-cabeza-de-marciano-certificada-6-26-quilates.md
- products/esmeralda-trapiche-certificada-4-06-quilates.md
- products/espinela-tratada-piedra-cultivada-3.03-quilates.md
- products/estrella-de-mar-fosil-100-natural-104-gramos.md
- products/fluorita-morada-piedra-preciosa-221-gramos.md
- products/fluorita-piedra-100-natural-9.40-quilates.md
- products/fluorita-piedra-natural-323-gramos.md
- products/fluorita-rosa-piedra-natural-392.80-quilates.md
- products/fosil-de-pirita-100-natural-151-quilates.md
- products/geoda-de-amatista-piedra-100-natural-213-gramos.md
- products/granate-henossita-piedra-100-natural-0.88-quilates.md
- products/granate-henossita-piedra-100-natural-2.92-quilates.md
- products/granate-henossita-piedra-100-natural-3.83-quilates-1.md
- products/granate-henossita-piedra-100-natural-3.83-quilates.md
- products/granate-piedra-100-natural-3.50-quilates.md
- products/henossita-natural-piedra-preciosa-1-85-quilates-150-000.md
- products/hueso-fosil-100-natural-104-gramos.md
- products/hypersteam-piedra-100-natural-19.15-quilates.md
- products/itrosenita-fluorita-muy-rara-345-gramos.md
- products/jade-dije-natural-291-80-quilates.md
- products/jaspe-oceanico-dije-100-natural-106-quilates.md
- products/jaspe-paisajita.md
- products/jaspe-piedra-100-natural-325.55-quilates.md
- products/kunsita-piedra-100-natural-22.55-quilates.md
- products/lapislazuli-piedra-100-natural-22.30-quilates.md
- products/lapislazuli-piedra-100-natural-44.65-quilates.md
- products/lote-2-diamantes-100-naturales-0-51-quilates.md
- products/lote-de-31-diamantes-1-23-quilates-piedra-100-natural.md
- products/lote-de-64-diamantes-0-95-quilates-piedra-100-natural.md
- products/lote-piedra-luna-100-natural-5.62-quilates.md
- products/malaquita-piedra-100-natural-35.40-quilates.md
- products/malaquita-piedra-100-natural-45.35-quilates.md
- products/malaquita-piedra-100-natural-51-quilates.md
- products/meteorito-metalico-19-quilates.md
- products/meteorito-moldavita-piedra-preciosa-15.90-quilates.md
- products/meteorito-moldavita-piedra-preciosa-19.90-quilates.md
- products/nuumita-1.md
- products/nuumita.md
- products/obelisco-cuarzo-ahumado-piedra-natural-260-quilates.md
- products/obsidiana-arco-iris-piedra-natural-397-quilates.md
- products/ojo-de-buey-piedra-100-natural-28-30-quilates.md
- products/ojo-de-tigre-piedra-100-natural-172-quilates.md
- products/opalina-piedra-preciosa-135.70-quilates.md
- products/opalo-australiano.md
- products/opalo-de-cantera-piedra-100-natural-21.85-quilate.md
- products/palasita-meteorito-220-quilates.md
- products/pendulo-en-lluvia-de-plata-y-cornalina.md
- products/peridoto-piedra-cultivada-50.15-quilates-1.md
- products/peridoto-piedra-cultivada-50.15-quilates.md
- products/perla-negra-1.md
- products/perla-negra-12-quilates.md
- products/perla-negra.md
- products/piedra-ara-100-natural-115.00-quilates.md
- products/piedra-ara-100-natural-7-quilates.md
- products/piedra-ara-100-natural-8-quilates.md
- products/piedra-ara-100-natural-9-quilates.md
- products/piedra-cristal-negro-tectita-19.72-quilates.md
- products/piedra-esfera-calcita-amarilla-237-gramos.md
- products/piedra-esfera-cuarzo-bismuto-245-quilates.md
- products/piedra-esfera-cuarzo-citrino-466.70-ct.md
- products/piedra-onix-cielo-piedra-natural-kilo-50-000.md
- products/piedra-preciosa-amatista-herkimer-93-85-quilates.md
- products/piedra-preciosa-azurita-con-malaquita-439-quilates.md
- products/piedra-preciosa-coral-fosilizado-87.20-quilates.md
- products/piedra-preciosa-cuarzo-lemuriano-rojo-127-40-quilates.md
- products/piedra-preciosa-cuarzo-negro-rumano-160-90-quilates.md
- products/piedra-preciosa-feldespato-natural-417.15-quilates.md
- products/piedra-preciosa-ojo-de-tigre-152-22-quilates.md
- products/piedra-preciosa-oropimente-natural-114-gramos.md
- products/piedra-preciosa-topacio-ahumado-aaa-5.01-ct.md
- products/piedra-preciosa-topacio-ahumado-aaa-5.20-quilates.md
- products/piedra-sagrada-ara-10.60-qt.md
- products/quiastolita-piedra-natural-34-quilates.md
- products/rebanada-agata-100-natural-62-quilates.md
- products/rebanada-de-agata-100-natural-56-quilates.md
- products/rodocrosita-piedra-natural-12-quilates.md
- products/rodocrosita-piedra-natural-26.19-quilates.md
- products/rodocrosita-piedra-natural-26.30-quilates.md
- products/rodocrosita-piedra-preciosa-143.15-quilates.md
- products/rodocrosita-piedra-preciosa-99.45-quilates.md
- products/rubi-estrella-certificado-4-73-quilates.md
- products/rubi-estrella-certificado-5.05-quilates.md
- products/rubi-estrella-piedra-preciosa-natural-9.31-quilate.md
- products/rubi-natural.md
- products/scapolita-100-natural-69.10-quiltates.md
- products/topacio-1.md
- products/topacio-mistico-3a-piedra-preciosa-3.56-quilates.md
- products/topacio.md
- products/turritella-fosil-100-natural-60-quilates.md
- products/turritella-fosil-100-natural-75-quilates.md
- products/vertebra-de-amonita-fosil-100-natural-270-quilates.md
- products/xilopalo-piedra-100-natural-100-gramos.md
- products/zafiro-corindon-estrella-certificado-3.16-quilates-1.md
- products/zafiro-corindon-estrella-certificado-3.16-quilates.md
- products/zafiro-corindon-piedra-100-natural-0.75-quilates.md
- products/zafiro-estrella-certificado-10.07-quilates.md
- products/zafiro-estrella-certificado-8.45-quilates.md
- products/zafiro-estrella-certificado-piedra-preciosa-5.90-quilates.md
- products/zafiro-estrella-piedra-preciosa-cultivada-2.53-ct.md
- products/zafiro-piedra-100-natural-0.63-quilates.md
- products/zircon-certificado-piedra-preciosa-9-68-quilates.md
- products/zoisita-dije-piedra-100-natural-19-quilates.md
- products/zoisita-piedra-100-natural-20-quilates.md
- products/zoisita-piedra-100-natural-39.40-quilates.md
- products/ágata-de-seda-piedra-natural-445-quilates.md
- products/ágata-de-seda-rosada-piedra-natural-370-quilates.md
